In [1]:
import numpy as np
import pandas as pd

In [2]:

df = pd.read_csv(r'C:\Users\U-ser\AMS_project\deploymentml\loan_elig.csv')

In [3]:
data = df.copy()

In [4]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
ApplicantIncome,614.0,5403.459283,6109.041673,150.0,2877.5,3812.5,5795.00,81000.0
CoapplicantIncome,614.0,1621.245798,2926.248369,0.0,0.0,1188.5,2297.25,41667.0
LoanAmount,592.0,146.412162,85.587325,9.0,100.0,128.0,168.00,700.0
Loan_Amount_Term,600.0,342.000000,65.120410,12.0,360.0,360.0,360.00,480.0
Credit_History,564.0,0.842199,0.364878,0.0,1.0,1.0,1.00,1.0

In [5]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
# Categorical
data['Gender']=data['Gender'].fillna(data['Gender'].mode()[0])
data['Married']=data['Married'].fillna(data['Married'].mode()[0])
data['Dependents']=data['Dependents'].fillna(data['Dependents'].mode()[0])
data['Loan_Amount_Term']=data['Loan_Amount_Term'].fillna(data['Loan_Amount_Term'].mode()[0])
data['Credit_History']=data['Credit_History'].fillna(data['Credit_History'].mode()[0])
data['Self_Employed']=data['Self_Employed'].fillna(data['Self_Employed'].mode()[0])

# Numerical
data['LoanAmount']=data['LoanAmount'].fillna(data['LoanAmount'].mean())
print("Modified df_train:")
print(data.isnull().sum())

print("\nModified df_test:")
print(data.isnull().sum())

Modified df_train:
Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

Modified df_test:
Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [7]:
# Selecting numerical columns
numerical_columns = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']

# Apply logarithmic transformation to numerical features
for column in numerical_columns:
    data[column + '_log'] = np.log(data[column] + 1)  # Adding 1 to avoid log(0)

In [8]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,ApplicantIncome_log,CoapplicantIncome_log,LoanAmount_log,Loan_Amount_Term_log
0,LP001002,Male,No,0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban,Y,8.674197,0.000000,4.993232,5.888878
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N,8.430327,7.319202,4.859812,5.888878
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y,8.006701,0.000000,4.204693,5.888878
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y,7.857094,7.765993,4.795791,5.888878
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y,8.699681,0.000000,4.955827,5.888878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.000000,360.0,1.0,Rural,Y,7.972811,0.000000,4.276666,5.888878
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.000000,180.0,1.0,Rural,Y,8.320448,0.000000,3.713572,5.198497
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.000000,360.0,1.0,Urban,Y,8.996280,5.484797,5.537334,5.888878
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.000000,360.0,1.0,Urban,Y,8.933796,0.000000,5.236442,5.888878
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.000000,360.0,0.0,Semiurban,N,8.430327,0.000000,4.897840,5.888878

In [9]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression

In [10]:
# List of columns to encode
columns_to_encode = ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area', 'Loan_Status']

# Apply label encoding to each column
for column in columns_to_encode:
    label_encoder = LabelEncoder()  # Create a new instance for each column
    data[column + "_Encode"] = label_encoder.fit_transform(data[column])

In [11]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,...,ApplicantIncome_log,CoapplicantIncome_log,LoanAmount_log,Loan_Amount_Term_log,Gender_Encode,Married_Encode,Education_Encode,Self_Employed_Encode,Property_Area_Encode,Loan_Status_Encode
0,LP001002,Male,No,0,Graduate,No,5849,0.0,146.412162,360.0,...,8.674197,0.000000,4.993232,5.888878,1,0,0,0,2,1
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.000000,360.0,...,8.430327,7.319202,4.859812,5.888878,1,1,0,0,0,0
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.000000,360.0,...,8.006701,0.000000,4.204693,5.888878,1,1,0,1,2,1
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.000000,360.0,...,7.857094,7.765993,4.795791,5.888878,1,1,1,0,2,1
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.000000,360.0,...,8.699681,0.000000,4.955827,5.888878,1,0,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.000000,360.0,...,7.972811,0.000000,4.276666,5.888878,0,0,0,0,0,1
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.000000,180.0,...,8.320448,0.000000,3.713572,5.198497,1,1,0,0,0,1
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.000000,360.0,...,8.996280,5.484797,5.537334,5.888878,1,1,0,0,2,1
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.000000,360.0,...,8.933796,0.000000,5.236442,5.888878,1,1,0,0,2,1
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.000000,360.0,...,8.430327,0.000000,4.897840,5.888878,0,0,0,1,1,0

In [12]:
datac = data.copy() # Copy the data to a new variable so that it won't affect the original data

In [13]:
datac.dtypes

Loan_ID                   object
Gender                    object
Married                   object
Dependents                object
Education                 object
Self_Employed             object
ApplicantIncome            int64
CoapplicantIncome        float64
LoanAmount               float64
Loan_Amount_Term         float64
Credit_History           float64
Property_Area             object
Loan_Status               object
ApplicantIncome_log      float64
CoapplicantIncome_log    float64
LoanAmount_log           float64
Loan_Amount_Term_log     float64
Gender_Encode              int32
Married_Encode             int32
Education_Encode           int32
Self_Employed_Encode       int32
Property_Area_Encode       int32
Loan_Status_Encode         int32
dtype: object

In [14]:
# Convert specific columns to float64
columns_to_convert = [
    'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term',
    'Credit_History', 'ApplicantIncome_log', 'CoapplicantIncome_log',
    'LoanAmount_log', 'Loan_Amount_Term_log'
]
datac[columns_to_convert] = datac[columns_to_convert].astype('float64')

In [15]:
#drop columns of original data
datac = datac.drop(columns=['Dependents', 'Loan_ID', 'Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area', 'Loan_Status', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount','Loan_Amount_Term'])

In [16]:
#choose x and y for model
x = datac.drop(columns=['Loan_Status_Encode', 'Gender_Encode', 'Married_Encode', 'Education_Encode', 'Self_Employed_Encode', 'Property_Area_Encode'])
y = datac['Loan_Status_Encode']

In [17]:
x

,Credit_History,ApplicantIncome_log,CoapplicantIncome_log,LoanAmount_log,Loan_Amount_Term_log
0,1.0,8.674197,0.000000,4.993232,5.888878
1,1.0,8.430327,7.319202,4.859812,5.888878
2,1.0,8.006701,0.000000,4.204693,5.888878
3,1.0,7.857094,7.765993,4.795791,5.888878
4,1.0,8.699681,0.000000,4.955827,5.888878
...,...,...,...,...,...
609,1.0,7.972811,0.000000,4.276666,5.888878
610,1.0,8.320448,0.000000,3.713572,5.198497
611,1.0,8.996280,5.484797,5.537334,5.888878
612,1.0,8.933796,0.000000,5.236442,5.888878
613,0.0,8.430327,0.000000,4.897840,5.888878

In [18]:
y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status_Encode, Length: 614, dtype: int32

In [19]:
#scale data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x = scaler.fit_transform(x)

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2024)

In [21]:
x_train

array([[0.        , 0.54305198, 0.        , 0.61065926, 0.92052178],
       [1.        , 0.35914437, 0.        , 0.30140167, 0.92052178],
       [1.        , 0.5322083 , 0.        , 0.54413587, 0.92052178],
       ...,
       [1.        , 0.59659819, 0.        , 0.6494259 , 0.72932914],
       [1.        , 0.48749669, 0.71220732, 0.56207204, 0.92052178],
       [1.        , 0.78394768, 0.82774003, 0.91137707, 0.92052178]])

In [22]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((491, 5), (123, 5), (491,), (123,))

In [23]:
type(x_train)

numpy.ndarray

In [24]:
model = LogisticRegression(max_iter=1000)	# Increase the number of iterations for convergence
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [25]:
# Make predictions
y_pred = model.predict(x_test)
y_proba = model.predict_proba(x_test)[:, 1]  # Probabilities of positive class for AUC-ROC

In [26]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, classification_report, confusion_matrix
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_proba)

# Print evaluation metrics
# Calculate confusion matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
# Calculate specificity
specificity = tn / (tn + fp)

print("Specificity for Logistic Regression:", specificity)
print("Logistic Regression Model Evaluation:")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("ROC AUC:", roc_auc)
print(classification_report(y_test, y_pred))

Specificity for Logistic Regression: 0.5757575757575758
Logistic Regression Model Evaluation:
Accuracy: 0.8699186991869918
Precision: 0.8627450980392157
Recall: 0.9777777777777777
F1-score: 0.9166666666666666
ROC AUC: 0.7888888888888889
              precision    recall  f1-score   support

           0       0.90      0.58      0.70        33
           1       0.86      0.98      0.92        90

    accuracy                           0.87       123
   macro avg       0.88      0.78      0.81       123
weighted avg       0.87      0.87      0.86       123

In [27]:
# Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[19 14]
 [ 2 88]]

In [28]:
import joblib

# Save the model
joblib.dump(model, 'model.pkl')

# Save the scaler
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']